[build]
  command = "npm run build"
  publish = ".next"
  environment = { SECRETS_SCAN_ENABLED = "false" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
